### ISSUE TITLE
UIScrollViewDelegate

### ISSUE THREAD

**Issue by makleso6** [DenTelezhkin/DTCollectionViewManager#35]
Hi! Thanks for great lib
How to listen UIScrollViewDelegate methods?

**Comment by makleso6** [comment]
I think to create objc NSProxy forwarding solved problem

**Comment by DenTelezhkin** [comment]
Hey!

Method forwarding is [already setup](https://github.com/DenTelezhkin/DTCollectionViewManager/blob/master/Source/DTCollectionViewDelegateWrapper.swift#L234-L252) in the framework, so just conform for example UIViewController to UIScrollViewDelegate and it should work:

```swift
class ViewController: UIViewController, DTCollectionViewManageable, UIScrollViewDelegate {
  override viewDidLoad() {
    super.viewDidLoad()
    manager.startManaging(withDelegate: self)
  }

  func scrollViewDidScroll(_ scrollView: UIScrollView) {
    print("did scroll")
  }
}
```

**Comment by makleso6** [comment]
Thanks!!!
i missed it 😅
