### ISSUE TITLE
Quick start updates

### ISSUE THREAD

**Issue by vladimir-trib** [DenTelezhkin/DTCollectionViewManager#37]
DTCollectionViewManageable doesn't work with outlets like *@IBOutlet weak var collectionView: UICollectionView!*. Please, updates the Quick start documentation to use the following protocol DTCollectionViewNonOptionalManageable instead of the DTCollectionViewManageable for @Outlet. Thanks.

**Comment by DenTelezhkin** [comment]
Hi! The readme was updated to reflect code for the 7.0.0-beta, that does not have DTCollectionViewNonOptionalManageable protocol anymore.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
